export const ADD_INTERVIEW_SUCCESS = 'ADD_INTERVIEW_SUCCESS';
export const ADD_INTERVIEW_FAILURE = 'ADD_INTERVIEW_FAILURE';
export const ADD_INTERVIEW_STARTED = 'ADD_INTERVIEW_STARTED';
export const GET_INTERVIEWS_SUCCESS = 'GET_INTERVIEWS_SUCCESS';
export const GET_INTERVIEWS_FAILURE = 'GET_INTERVIEWS_FAILURE';
export const GET_INTERVIEWS_STARTED = 'GET_INTERVIEWS_STARTED';